/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cstdint>
#include <algorithm>
#include <map>
#include <mutex>

#include "acl/acl.h"
#include "ops.h"
#include "hifloat8_cast_tiling.h"
#include "securec.h"
#include "tiling/platform/platform_ascendc.h"
#include "torch_npu/csrc/core/npu/NPUStream.h"

// Host stub generated by ASC compiler from op_kernel/hifloat8_cast_kernel.cpp.
extern "C" void hifloat8_cast_kernel_lut(uint32_t blockDim, void *l2Ctrl, aclrtStream stream, uint8_t *input,
    uint8_t *output, uint8_t *tiling, uint8_t *lutGm);

namespace {
constexpr uint32_t FP16_EXP_BITS = 5;
constexpr uint32_t FP16_FRAC_BITS = 10;
constexpr uint32_t FP16_EXP_BIAS = 15;

constexpr uint32_t BF16_EXP_BITS = 8;
constexpr uint32_t BF16_FRAC_BITS = 7;
constexpr uint32_t BF16_EXP_BIAS = 127;

constexpr uint32_t HIF8_SIGN_SHIFT = 7;
constexpr uint32_t HIF8_DENORMAL_EXP_BIAS = 23;
constexpr uint8_t HIF8_POSITIVE_MIN_NORMAL = 0x7E;

constexpr uint32_t HIF8_DOT_TABLE[16] = {
    (0x00 << 24) | (3 << 16) | (0 << 8) | (0 << 4) | 7,
    (0x00 << 24) | (3 << 16) | (1 << 8) | (0 << 4) | 7,
    (0x08 << 24) | (3 << 16) | (3 << 8) | (1 << 4) | 7,
    (0x08 << 24) | (3 << 16) | (3 << 8) | (1 << 4) | 7,
    (0x18 << 24) | (3 << 16) | (4 << 8) | (2 << 4) | 7,
    (0x18 << 24) | (3 << 16) | (4 << 8) | (2 << 4) | 7,
    (0x18 << 24) | (3 << 16) | (4 << 8) | (2 << 4) | 7,
    (0x18 << 24) | (3 << 16) | (4 << 8) | (2 << 4) | 7,
    (0x1c << 24) | (2 << 16) | (4 << 8) | (3 << 4) | 3,
    (0x1c << 24) | (2 << 16) | (4 << 8) | (3 << 4) | 3,
    (0x1c << 24) | (2 << 16) | (4 << 8) | (3 << 4) | 3,
    (0x1c << 24) | (2 << 16) | (4 << 8) | (3 << 4) | 3,
    (0x1e << 24) | (1 << 16) | (4 << 8) | (4 << 4) | 1,
    (0x1e << 24) | (1 << 16) | (4 << 8) | (4 << 4) | 1,
    (0x1e << 24) | (1 << 16) | (4 << 8) | (4 << 4) | 1,
    (0x1e << 24) | (1 << 16) | (4 << 8) | (4 << 4) | 1,
};
}

static uint32_t HostHif8ToFpBits(uint8_t inData, uint32_t expBits, uint32_t fracBits, uint32_t expBias) {
    if (inData == 0) {
        return 0;
    }

    uint32_t expMax = (1u << expBits) - 1;
    if (inData == 0x80)
        return (expMax << fracBits) | ((1u << fracBits) - 1);
    if (inData == 0x6F)
        return expMax << fracBits;
    if (inData == 0xEF)
        return (1u << 15) | (expMax << fracBits);  // 15: FP16/BF16符号位位置

    uint8_t dot = (inData & 0x78) >> 3;
    uint32_t info = HIF8_DOT_TABLE[dot];

    uint8_t expMask = (info >> 24) & 0xFF;
    uint8_t fracHiF8Bits = (info >> 16) & 0xFF;
    uint8_t expSignShift = (info >> 8) & 0xFF;
    uint8_t expHiF8Bits = (info >> 4) & 0x0F;
    uint8_t fracMask = info & 0x0F;

    uint32_t expHiF8 = (inData & expMask) >> fracHiF8Bits;
    uint32_t signExp = (inData >> expSignShift) & 0x01;
    uint32_t fracFpN = inData & fracMask;
    uint32_t expFpN = 0;
    uint32_t sign = inData >> HIF8_SIGN_SHIFT;

    if (expSignShift == 0) {
        int32_t biasedExp = static_cast<int32_t>(expBias) - static_cast<int32_t>(HIF8_DENORMAL_EXP_BIAS - fracFpN);
        if (biasedExp <= 0) {
            int32_t shift = biasedExp - 1 + static_cast<int32_t>(fracBits);
            uint32_t mantissa = (shift >= 0) ? (1u << static_cast<uint32_t>(shift)) : 0u;
            return (sign << 15) | mantissa;  // 15: FP16/BF16符号位位置
        }
        expFpN = static_cast<uint32_t>(biasedExp);
        fracFpN = 0;
    } else if (expSignShift == 1) {
        expFpN = expBias;
    } else {
        int32_t expNoBias = static_cast<int32_t>((expHiF8 | (1u << (expHiF8Bits - 1))) * (signExp == 1 ? -1 : 1));
        int32_t biasedExp = expNoBias + static_cast<int32_t>(expBias);
        if (biasedExp <= 0) {
            int32_t shift = biasedExp - 1 + static_cast<int32_t>(fracBits) - static_cast<int32_t>(fracHiF8Bits);
            uint32_t S = (1u << fracHiF8Bits) | fracFpN;
            uint32_t mantissa =
                (shift >= 0) ? (S << static_cast<uint32_t>(shift)) : (S >> static_cast<uint32_t>(-shift));
            return (sign << 15) | mantissa;  // 15: FP16/BF16符号位位置
        }
        expFpN = static_cast<uint32_t>(biasedExp);
    }

    return (sign << 15) | (expFpN << fracBits) | (fracFpN << (fracBits - fracHiF8Bits));  // 15: FP16/BF16符号位位置
}

static at::Tensor BuildLut8Cpu(int64_t castMode) {
    bool isFP16 = (castMode == HIF8_TO_FP16);
    uint32_t expBits = isFP16 ? FP16_EXP_BITS : BF16_EXP_BITS;
    uint32_t fracBits = isFP16 ? FP16_FRAC_BITS : BF16_FRAC_BITS;
    uint32_t expBias = isFP16 ? FP16_EXP_BIAS : BF16_EXP_BIAS;

    at::Tensor lut = at::empty({LUT8_SIZE}, at::device(at::kCPU).dtype(at::kUInt16));
    uint16_t *data = lut.data_ptr<uint16_t>();
    for (uint32_t i = 0; i < LUT8_SIZE; i++) {
        data[i] = static_cast<uint16_t>(HostHif8ToFpBits(static_cast<uint8_t>(i), expBits, fracBits, expBias));
    }
    return lut;
}

// ── Host-side LUT helpers ─────────────────────────────────────────────────────
// Run on CPU to precompute the 32768-entry encode LUT once per mode.
static void HostGetHif8BitsNum(int32_t expNoBias, uint32_t &dotValue, uint32_t &expBitsOut, uint32_t &fracBitsOut) {
    int32_t absExp = expNoBias < 0 ? -expNoBias : expNoBias;
    if (expNoBias == 0) {
        dotValue = 0x01;
        expBitsOut = 0;
        fracBitsOut = 3;  // 3: HiFloat8尾数位数，dotValue=1场景
    } else if (absExp == 1) {
        dotValue = 0x02;
        expBitsOut = 1;
        fracBitsOut = 3;  // 3: HiFloat8尾数位数，dotValue=2场景
    } else if (absExp >= 2 && absExp <= 3) {  // HiFloat8指数区间[2, 3]
        dotValue = 0x04;
        expBitsOut = 2;   // 2: HiFloat8指数位数，dotValue=4场景
        fracBitsOut = 3;  // 3: HiFloat8尾数位数，dotValue=4场景
    } else if (absExp >= 4 && absExp <= 7) {  // HiFloat8指数区间[4, 7]
        dotValue = 0x08;
        expBitsOut = 3;   // 3: HiFloat8指数位数，dotValue=8场景
        fracBitsOut = 2;  // 2: HiFloat8尾数位数，dotValue=8场景
    } else {
        dotValue = 0x0C;
        expBitsOut = 4;   // 4: HiFloat8指数位数，dotValue=0xc场景
        fracBitsOut = 1;  // 1: HiFloat8尾数位数，dotValue=0xc场景
    }
}

static uint8_t HostFp32MagnitudeToHif8(uint32_t inData) {
    uint32_t expFp = (inData >> 23) & 0xFF;  // 23: FP32尾数位数
    uint32_t fracFp = inData & 0x7FFFFF;
    // Host LUT 只编码正数幅值，符号位由 device encode 阶段补回。
    if (expFp == 0)
        return 0x00;
    if (expFp == 255)  // 255: FP32指数最大值（全1）
        return fracFp > 0 ? 0x80 : 0x6F;

    int32_t expNoBias = static_cast<int32_t>(expFp) - 127;  // 127: FP32指数偏置
    // 超出 HiFloat8 表示范围时，饱和到最大正有限值。
    if (expNoBias >= 15)  // 15: HiFloat8最大指数
        return 0x6E;

    // HiFloat8 denormal 区间；过小值归零，边界值保留最小非零编码。
    if (expNoBias < -15) {  // 15: HiFloat8最大指数
        if (expNoBias < -23)  // 23: FP32尾数位数
            return 0x00;
        if (expNoBias == -23)  // 23: FP32尾数位数
            return 0x01;

        uint32_t fracHiF8 = static_cast<uint32_t>(HIF8_DENORMAL_EXP_BIAS + expNoBias);
        if ((fracFp >> 22) >= 1u)  // 22: FP32尾数位数-1
            ++fracHiF8;
        return fracHiF8 >= 8u ? HIF8_POSITIVE_MIN_NORMAL : static_cast<uint8_t>(fracHiF8);  // 8: HiFloat8非规格化数最大值
    }
    uint32_t dotValue = 0;
    uint32_t expHiF8Bits = 0;
    uint32_t fracHiF8Bits = 0;
    HostGetHif8BitsNum(expNoBias, dotValue, expHiF8Bits, fracHiF8Bits);
    uint32_t fracShift = 23 - fracHiF8Bits - 1;  // 23: FP32尾数位数
    uint32_t fractmp = fracFp >> fracShift;
    uint32_t fracMax = (1u << (fracHiF8Bits + 1)) - 1;
    uint32_t fracHiF8 = 0;
    // 多取 1 bit 作为舍入位；尾数溢出时进位到下一个指数段。
    if (fractmp == fracMax) {
        expNoBias += 1;
        HostGetHif8BitsNum(expNoBias, dotValue, expHiF8Bits, fracHiF8Bits);
    } else if ((fractmp & 0x01) == 0x01) {
        fracHiF8 = (fractmp + 1) >> 1;
    } else {
        fracHiF8 = fractmp >> 1;
    }
    if (dotValue == 1)
        return static_cast<uint8_t>((dotValue << fracHiF8Bits) | fracHiF8);
    int32_t absExpFinal = expNoBias < 0 ? -expNoBias : expNoBias;
    uint32_t signExp = expNoBias < 0 ? 1u : 0u;
    uint32_t expHiF8 = static_cast<uint32_t>(absExpFinal) - (1u << (expHiF8Bits - 1));
    // 3：dot value移动到[6:3]位置，再拼接 dot、指数符号、指数幅值和尾数，得到无数值符号位的 HiFloat8 编码。
    return static_cast<uint8_t>(
        (dotValue << 3) | (signExp << (expHiF8Bits + fracHiF8Bits - 1)) | (expHiF8 << fracHiF8Bits) | fracHiF8);
}

// Build 32768-entry encode LUT on CPU for FP16 or BF16.
// Positive half only (sign bit stripped): key = absBits = val & 0x7FFF, value = magnitude.
// Sign is re-applied in ComputeEncode16.
static at::Tensor BuildLut16Cpu(int64_t castMode) {
    bool isFP16 = (castMode == FP16_TO_HIF8);
    uint32_t expBias = isFP16 ? 15u : 127u;
    uint32_t expBitsN = isFP16 ? 5u : 8u;
    uint32_t fracBitsN = isFP16 ? 10u : 7u;

    at::Tensor lut = at::empty({LUT16_SIZE}, at::device(at::kCPU).dtype(at::kByte));
    uint8_t *data = lut.data_ptr<uint8_t>();
    for (uint32_t i = 0; i < LUT16_SIZE; i++) {
        uint16_t val = static_cast<uint16_t>(i); // sign bit always 0
        uint32_t exp = (val >> fracBitsN) & ((1u << expBitsN) - 1);
        uint32_t frac = val & ((1u << fracBitsN) - 1);
        uint32_t fp32Bits = 0u;
        if (exp == 0) {
            // Subnormal: no implicit leading 1; normalize by finding the leading 1 in frac.
            if (frac == 0) {
                fp32Bits = 0u;
            } else {
                // p: position of leading 1 bit; __builtin_clz is UB for 0, guarded above.
                uint32_t p = 31u - static_cast<uint32_t>(__builtin_clz(frac));  // 31: uint32_t位数-1
                // fp32Exp = (1 - expBias) + (p - fracBitsN) + 127
                int32_t fp32Exp = static_cast<int32_t>(p) - static_cast<int32_t>(fracBitsN) -
                                  static_cast<int32_t>(expBias - 1u) + 127;  // 127: FP32指数偏置
                uint32_t fp32Frac = (frac & ((1u << p) - 1u)) << (23u - p);  // 23: FP32尾数位数
                fp32Bits = (fp32Exp > 0) ? ((static_cast<uint32_t>(fp32Exp) << 23) | fp32Frac) : 0u;  // 23: FP32尾数位数
            }
        } else {
            // exp 全 1 表示 Inf/NaN：必须显式映射到 FP32 exp=255，
            // 否则 FP16 的 exp=31 会被加上 (127-15)=112 偏置变为 143，丢掉特殊值语义。
            uint32_t expMaxN = (1u << expBitsN) - 1;
            uint32_t expFp32 = (exp == expMaxN) ? 255u : (exp + (127u - expBias));  // 255/127: FP32指数最大值/偏置
            fp32Bits = (expFp32 << 23) | (frac << (23u - fracBitsN));  // 23: FP32尾数位数
        }
        data[i] = HostFp32MagnitudeToHif8(fp32Bits); // magnitude only, no sign
    }
    return lut;
}

// ── Torch binding ──────────────────────────────────────────────────────────────

static uint32_t GetAivCoreNum() {
    auto *platform = platform_ascendc::PlatformAscendCManager::GetInstance();
    if (platform == nullptr)
        return 32u;  // 32: 默认AIV核数
    uint32_t n = platform->GetCoreNumAiv();
    return n > 0u ? n : 32u;  // 32: 默认AIV核数
}

static uint32_t GetUbSizeBytes() {
    auto *platform = platform_ascendc::PlatformAscendCManager::GetInstance();
    if (platform == nullptr)
        return 256u * 1024u;  // 256KB: 默认UB大小
    uint64_t ub = 0;
    platform->GetCoreMemSize(platform_ascendc::CoreMemType::UB, ub);
    return ub > 0u ? static_cast<uint32_t>(ub) : 256u * 1024u;  // 256KB: 默认UB大小
}

static uint32_t ComputeMaxTileLength(uint32_t ubBytes, bool isEncode) {
    uint32_t lutBytes = isEncode ? LUT16_SIZE : (LUT8_SIZE * 2u);
    // UB 连 LUT 都放不下，硬件配置异常
    TORCH_CHECK(ubBytes > lutBytes, "UB too small to hold LUT");
    // 每个元素占 3 字节 UB：encode/decode 的 input + output 之和（FP16/BF16 是 2B，HiF8 是 1B）。
    // 单缓冲（TQue depth=1, InitBuffer num=1）—— 标量循环主导，MTE/Compute 重叠收益为 0。
    uint32_t maxTile = (ubBytes - lutBytes) / 3u;
    // UB 剩余空间不足一个最小 tile（32 元素），硬件配置异常
    TORCH_CHECK(maxTile >= 32u, "UB too small to hold minimum tile");
    maxTile = std::min(maxTile, 65536u); // A3 UB 实测最大可用 tile
    // ≥ 32768 时对齐到 32768 的整数倍，使 CopyIn 大块走 Case B（{n, 32768}），
    // 避免 DataCopyParams.blockLen(uint16_t) 溢出
    if (maxTile >= 32768u) {  // 32768: tile对齐阈值，避免blockLen溢出
        return (maxTile / 32768u) * 32768u;
    }
    return std::max((maxTile / 32u) * 32u, 32u); // 小 tile 对齐到 32（向量指令粒度）
}

static uint32_t ComputeNumBlocks(uint64_t totalElements, uint32_t maxBlocks, uint32_t minPerCore) {
    TORCH_CHECK(minPerCore > 0u, "minPerCore must be positive");
    uint64_t idealBlocks64 = totalElements / minPerCore;
    idealBlocks64 = std::min(idealBlocks64, static_cast<uint64_t>(maxBlocks));
    uint32_t idealBlocks = static_cast<uint32_t>(idealBlocks64);
    return std::max(idealBlocks, 1u);
}

static void ValidateInput(const at::Tensor &input, int64_t castMode) {
    TORCH_CHECK(castMode >= FP16_TO_HIF8 && castMode <= HIF8_TO_BF16, "castMode must be in [0, 3]");
    TORCH_CHECK(input.device().type() == c10::DeviceType::PrivateUse1, "input must be on NPU device");
    if (castMode == FP16_TO_HIF8)
        TORCH_CHECK(input.dtype() == at::kHalf, "FP16_TO_HIF8 requires half input");
    if (castMode == BF16_TO_HIF8)
        TORCH_CHECK(input.dtype() == at::kBFloat16, "BF16_TO_HIF8 requires bfloat16 input");
    if (castMode >= HIF8_TO_FP16)
        TORCH_CHECK(input.dtype() == at::kByte, "decode modes require uint8 input");
}

static at::Tensor AllocateOutput(const at::Tensor &inputContiguous, int64_t castMode) {
    if (castMode <= BF16_TO_HIF8)
        return at::empty(inputContiguous.sizes(), inputContiguous.options().dtype(at::kByte));
    if (castMode == HIF8_TO_FP16)
        return at::empty(inputContiguous.sizes(), inputContiguous.options().dtype(at::kHalf));
    return at::empty(inputContiguous.sizes(), inputContiguous.options().dtype(at::kBFloat16));
}

static HiFloat8CastTilingData BuildTilingData(int64_t totalElements, int64_t castMode, bool isEncode) {
    uint32_t ubBytes = GetUbSizeBytes();
    uint32_t maxBlocks = GetAivCoreNum();
    uint32_t maxTileLen = ComputeMaxTileLength(ubBytes, isEncode);

    constexpr uint32_t MIN_PER_CORE_ENCODE = 4096u;
    constexpr uint32_t MIN_PER_CORE_DECODE = 2048u;
    uint32_t minPerCore = isEncode ? MIN_PER_CORE_ENCODE : MIN_PER_CORE_DECODE;

    uint32_t numBlocks = ComputeNumBlocks(totalElements, maxBlocks, minPerCore);
    uint64_t numPerCore = static_cast<uint64_t>(totalElements / numBlocks);
    uint64_t tailNum = static_cast<uint64_t>(totalElements - numPerCore * (numBlocks - 1));
    uint32_t tileLength =
        static_cast<uint32_t>(std::min(static_cast<uint64_t>(maxTileLen), static_cast<uint64_t>(numPerCore)));

    return {numBlocks, static_cast<uint64_t>(totalElements), numPerCore, tailNum, static_cast<uint32_t>(castMode),
        tileLength};
}

static at::Tensor UploadTilingToDevice(const HiFloat8CastTilingData &tilingHost, const at::Tensor &refTensor) {
    at::Tensor tilingTensor = at::empty({sizeof(HiFloat8CastTilingData)}, at::device(at::kCPU).dtype(at::kByte));
    errno_t ret = memcpy_s(tilingTensor.data_ptr(), tilingTensor.nbytes(), &tilingHost, sizeof(HiFloat8CastTilingData));
    TORCH_CHECK(ret == EOK, "copy tiling data to host tensor failed, memcpy_s ret: ", ret);
    return tilingTensor.to(refTensor.device());
}

// LUT 在首次使用时构建并搬到 device，进程生命周期内每种 castMode 只构建一次。
static uint8_t *GetOrBuildLutOnDevice(int64_t castMode, const at::Tensor &refTensor) {
    static std::mutex lutMutex;
    static std::map<std::pair<int64_t, int64_t>, at::Tensor> lutCache;

    int64_t deviceIndex = static_cast<int64_t>(refTensor.device().index());
    auto key = std::make_pair(deviceIndex, castMode);
    std::lock_guard<std::mutex> guard(lutMutex);
    auto it = lutCache.find(key);
    if (it != lutCache.end()) {
        return reinterpret_cast<uint8_t *>(it->second.data_ptr());
    }

    at::Tensor lut;
    switch (castMode) {
        case FP16_TO_HIF8: lut = BuildLut16Cpu(FP16_TO_HIF8).to(refTensor.device()); break;
        case BF16_TO_HIF8: lut = BuildLut16Cpu(BF16_TO_HIF8).to(refTensor.device()); break;
        case HIF8_TO_FP16: lut = BuildLut8Cpu(HIF8_TO_FP16).to(refTensor.device()); break;
        default: // HIF8_TO_BF16
            lut = BuildLut8Cpu(HIF8_TO_BF16).to(refTensor.device());
            break;
    }
    auto result = lutCache.emplace(key, std::move(lut));
    return reinterpret_cast<uint8_t *>(result.first->second.data_ptr());
}

namespace AscendKernel {

at::Tensor Hifloat8CastTorch(const at::Tensor &input, int64_t castMode) {
    ValidateInput(input, castMode);

    auto inputContiguous = input.contiguous();
    int64_t totalElements = inputContiguous.numel();
    TORCH_CHECK(totalElements > 0, "input tensor must not be empty");

    at::Tensor output = AllocateOutput(inputContiguous, castMode);
    bool isEncode = (castMode <= BF16_TO_HIF8);

    HiFloat8CastTilingData tilingHost = BuildTilingData(totalElements, castMode, isEncode);
    at::Tensor tilingDevice = UploadTilingToDevice(tilingHost, input);
    uint8_t *lutGm = GetOrBuildLutOnDevice(castMode, input);

    auto aclStream = c10_npu::getCurrentNPUStream().stream(true);
    hifloat8_cast_kernel_lut(tilingHost.blockNum, nullptr, aclStream,
        reinterpret_cast<uint8_t *>(inputContiguous.data_ptr()), reinterpret_cast<uint8_t *>(output.data_ptr()),
        reinterpret_cast<uint8_t *>(tilingDevice.data_ptr()), lutGm);

    return output;
}

} // namespace AscendKernel
